---

global:
  setting:
    tab_size: 4 # 4 spaces
  path:
    application: 'src/application'
    domain_model: 'src/domain_model'
    exception: 'src/domain_model/resource/exception'
    port_adapter: 'src/port_adapter'
    repository: 'src/port_adapter/repository'
    db_model: 'src/port_adapter/repository/db_model'
    messaging_listener: 'src/port_adapter/messaging/listener'
    grpc_api_listener: 'src/port_adapter/api/grpc/listener'
    proto_buffer: 'src/resource/proto'
    test: 'test'
    app_di: 'src/port_adapter'

domain_model:
  - model: &organization_model
      skip: [ all ]
      file_overwrite: True
      path: organization
      name: organization
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string
        - name: website_url
          type: str
          default: None
          proto:
            type: string
        - name: organization_type
          type: str
          default: None
          proto:
            type: string   
        - name: address_one
          type: str
          default: None
          proto:
            type: string
        - name: address_two
          type: str
          default: None
          proto:
            type: string            
        - name: postal_code
          type: str
          default: None
          proto:
            type: string
        - name: country_id
          type: int
          default: None
          proto:
            type: int32
        - name: city_id
          type: int
          default: None
          proto:
            type: int32
        - name: country_state_name
          type: str
          default: None
          proto:
            type: string          
        - name: country_state_iso_code
          type: str
          default: None
          proto:
            type: string 
        - name: manager_first_name
          type: str
          default: None
          proto:
            type: string          
        - name: manager_last_name
          type: str
          default: None
          proto:
            type: string         
        - name: manager_email
          type: str
          default: None
          proto:
            type: string     
        - name: manager_phone_number
          type: str
          default: None
          proto:
            type: string            
        - name: manager_avatar
          type: str
          default: None
          proto:
            type: string

  - model: &standard_equipment_project_category
      skip: []
      file_overwrite: True
      path: project/standard_equipment/standard_project/standard_category
      name: standard_equipment_project_category
      field:
        - name: name
          type: str
          default: None
          proto:
            type: string
          db:
            type: 'String(40)'

        - name: organization_id
          type: str
          default: None
          foreign:
            model: *organization_model
          proto:
            type: string
          db:
            type: 'String(40)'

segment:
  - name: standard_equipment_project_category
    foreign:
      model: *organization_model