"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""
from typing import List, Optional

from pydantic import BaseModel

from src.port_adapter.api.rest.model.response.v1.project.lookup.equipment.MaintenanceProcedureOperationParameter import \
    MaintenanceProcedureOperationParameter
from src.port_adapter.api.rest.model.response.v1.project.lookup.equipment.MaintenanceProcedureOperationLabel import \
    MaintenanceProcedureOperationLabel

class MaintenanceProcedureOperation(BaseModel):
    id: str
    name: str
    description: str
    type: str
    maintenance_procedure_operation_parameters: Optional[List[MaintenanceProcedureOperationParameter]]
    maintenance_procedure_operation_labels: Optional[List[MaintenanceProcedureOperationLabel]]



class MaintenanceProcedureOperationDescriptor(MaintenanceProcedureOperation):
    pass
