"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import Optional

from pydantic import BaseModel


class EquipmentInput(BaseModel):
    id: str
    name: str
    value: str
    unit_id: str


class EquipmentInputDescriptor(EquipmentInput):
    pass
