"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from pydantic import BaseModel

from src.port_adapter.api.rest.model.response.v1.project.daily_check.procedure.operation.DailyCheckProcedureOperation import (
    DailyCheckProcedureOperationDescriptor,
)


class DailyCheckProcedureOperations(BaseModel):
    daily_check_procedure_operations: List[DailyCheckProcedureOperationDescriptor]
    item_count: int
