"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from pydantic import BaseModel


class StandardMaintenanceProcedureOperationParameter(BaseModel):
    id: str
    name: str
    unit_id: str
    standard_maintenance_procedure_operation_id: str
    min_value: float
    max_value: float


class StandardMaintenanceProcedureOperationParameterDescriptor(
    StandardMaintenanceProcedureOperationParameter
):
    pass
