"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from pydantic import BaseModel

from src.port_adapter.api.rest.model.response.v1.project.daily_check.procedure.operation.parameter.DailyCheckProcedureOperationParameter import (
    DailyCheckProcedureOperationParameterDescriptor,
)


class DailyCheckProcedureOperationParameters(BaseModel):
    daily_check_procedure_operation_parameters: List[
        DailyCheckProcedureOperationParameterDescriptor
    ]
    total_item_count: int
