"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import Optional

from pydantic import BaseModel


class EquipmentCategoryGroup(BaseModel):
    id: str
    name: str
    equipment_category_id: str


class EquipmentCategoryGroupDescriptor(EquipmentCategoryGroup):
    pass
