version: "3.8"

services:
  cafm-api:
    image: cafm-api:local
    build:
      context: ../../..
      dockerfile: .pkg/local/docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      - GUNICORN_CMD_ARGS="--reload"  # Don't include - doesn't work
    # Use ONE of the two commands below to
    #   auto-reload when developing
    # will track everything in sys.path and can use a lot of CPU command: ["/start-reload.sh"]
    # will only track files in /app directory
    #  (can add additional paths with additional reload-dir options)
    entrypoint: ["uvicorn", "src.port_adapter.api.rest.main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app"]
    working_dir: /app
    network_mode: "host"
    volumes:
      - ../../..:/app

  cafm-api-rsp:
    image: cafm-api:local
    entrypoint: ["hupper", "python", "-m", "src.port_adapter.messaging.listener.ApiResponseListener"]
    working_dir: /app
    network_mode: "host"
    volumes:
      - ../../..:/app
    depends_on:
      - cafm-api
