"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import Optional

from pydantic import BaseModel


class MaintenanceProcedureOperationParameter(BaseModel):
    id: str
    name: str
    unit_id: str
    maintenance_procedure_operation_id: str
    min_value: float
    max_value: float


class MaintenanceProcedureOperationParameterDescriptor(
    MaintenanceProcedureOperationParameter
):
    pass
