"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import Optional

from pydantic import BaseModel


class StandardEquipmentCategoryGroup(BaseModel):
    id: str
    name: str
    standard_equipment_category_id: str


class StandardEquipmentCategoryGroupDescriptor(StandardEquipmentCategoryGroup):
    pass
