# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from project import maintenance_procedure_app_service_pb2 as project_dot_maintenance__procedure__app__service__pb2


class MaintenanceProcedureAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.maintenanceProcedureById = channel.unary_unary(
                '/cafm.project.maintenance_procedure.MaintenanceProcedureAppService/maintenanceProcedureById',
                request_serializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdRequest.SerializeToString,
                response_deserializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdResponse.FromString,
                )
        self.maintenanceProcedures = channel.unary_unary(
                '/cafm.project.maintenance_procedure.MaintenanceProcedureAppService/maintenanceProcedures',
                request_serializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresRequest.SerializeToString,
                response_deserializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresResponse.FromString,
                )


class MaintenanceProcedureAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def maintenanceProcedureById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def maintenanceProcedures(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MaintenanceProcedureAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'maintenanceProcedureById': grpc.unary_unary_rpc_method_handler(
                    servicer.maintenanceProcedureById,
                    request_deserializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdRequest.FromString,
                    response_serializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdResponse.SerializeToString,
            ),
            'maintenanceProcedures': grpc.unary_unary_rpc_method_handler(
                    servicer.maintenanceProcedures,
                    request_deserializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresRequest.FromString,
                    response_serializer=project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cafm.project.maintenance_procedure.MaintenanceProcedureAppService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MaintenanceProcedureAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def maintenanceProcedureById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.project.maintenance_procedure.MaintenanceProcedureAppService/maintenanceProcedureById',
            project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdRequest.SerializeToString,
            project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProcedureByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def maintenanceProcedures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cafm.project.maintenance_procedure.MaintenanceProcedureAppService/maintenanceProcedures',
            project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresRequest.SerializeToString,
            project_dot_maintenance__procedure__app__service__pb2.MaintenanceProcedureAppService_maintenanceProceduresResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
