"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from pydantic import BaseModel

from src.port_adapter.api.rest.model.response.v1.project.manufacturer.Manufacturer import (
    ManufacturerDescriptor,
)


class Manufacturers(BaseModel):
    manufacturers: List[ManufacturerDescriptor]
    total_item_count: int
