"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""



import os
from typing import List, Any

import grpc

import src.port_adapter.AppDi as AppDi
from src.port_adapter.api.rest.grpc.Client import Client
from src.port_adapter.api.rest.model.response.v1.project.maintenance.procedure.operation.label.MaintenanceProcedureOperationLabel import MaintenanceProcedureOperationLabelDescriptor
from src.port_adapter.api.rest.model.response.v1.project.maintenance.procedure.operation.label.MaintenanceProcedureOperationLabels import MaintenanceProcedureOperationLabels
from src.resource.logging.logger import logger
from src.resource.logging.opentelemetry.OpenTelemetry import OpenTelemetry
from src.resource.proto._generated.project.maintenance_procedure_operation_label_app_service_pb2 import \
    MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelsResponse, \
    MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelsRequest, MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelByIdRequest, \
    MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelByIdResponse, MaintenanceProcedureOperationLabelAppService_newIdResponse, \
    MaintenanceProcedureOperationLabelAppService_newIdRequest
from src.resource.proto._generated.project.maintenance_procedure_operation_label_app_service_pb2_grpc import MaintenanceProcedureOperationLabelAppServiceStub

class MaintenanceProcedureOperationLabelClient(Client):
    def __init__(self):
        self._server = os.getenv('CAFM_PROJECT_GRPC_SERVER_SERVICE', '')
        self._port = os.getenv('CAFM_PROJECT_GRPC_SERVER_SERVICE_PORT', '')

    @OpenTelemetry.grpcTraceOTel
    def newId(self) -> str:
        with grpc.insecure_channel(f'{self._server}:{self._port}') as channel:
            stub = MaintenanceProcedureOperationLabelAppServiceStub(channel)
            try:
                request = MaintenanceProcedureOperationLabelAppService_newIdRequest()
                response: MaintenanceProcedureOperationLabelAppService_newIdResponse = stub.new_id.with_call(
                    request,
                    metadata=(('token', self.token), (
                        'opentel', AppDi.instance.get(OpenTelemetry).serializedContext(
                            MaintenanceProcedureOperationLabelClient.newId.__qualname__))))
                logger.debug(
                    f'[{MaintenanceProcedureOperationLabelClient.newId.__qualname__}] - grpc response: {response}')
                return response[0].id
            except Exception as e:
                channel.unsubscribe(lambda ch: ch.close())
                raise e

    @OpenTelemetry.grpcTraceOTel
    def maintenanceProcedureOperationLabels(self, resultFrom: int = 0, resultSize: int = 10, orders: List[dict] = None) -> MaintenanceProcedureOperationLabels:
        orders = [] if orders is None else orders
        with grpc.insecure_channel(f'{self._server}:{self._port}') as channel:
            stub = MaintenanceProcedureOperationLabelAppServiceStub(channel)
            try:
                logger.debug(
                    f'[{MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabels.__qualname__}] - grpc call to retrieve maintenanceProcedureOperationLabels from server {self._server}:{self._port}')
                request = MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelsRequest(result_from=resultFrom, result_size=resultSize)
                [request.orders.add(order_by=o["orderBy"], direction=o["direction"]) for o in orders]
                response: MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelsResponse = stub.maintenance_procedure_operation_labels.with_call(
                    request,
                    metadata=(('token', self.token), (
                        'opentel',
                        AppDi.instance.get(OpenTelemetry).serializedContext(
                            MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabels.__qualname__)),))
                logger.debug(
                    f'[{MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabels.__qualname__}] - grpc response: {response}')

                return MaintenanceProcedureOperationLabels(maintenance_procedure_operation_labels=[self._descriptorByObject(obj=maintenanceProcedureOperationLabel) for maintenanceProcedureOperationLabel in
                                                    response[0].maintenance_procedure_operation_labels],
                                     total_item_count=response[0].total_item_count)
            except Exception as e:
                channel.unsubscribe(lambda ch: ch.close())
                raise e

    @OpenTelemetry.grpcTraceOTel
    def maintenanceProcedureOperationLabelById(self, id) -> MaintenanceProcedureOperationLabelDescriptor:
        with grpc.insecure_channel(f'{self._server}:{self._port}') as channel:
            stub = MaintenanceProcedureOperationLabelAppServiceStub(channel)
            try:
                logger.debug(
                    f'[{MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabelById.__qualname__}] - grpc call to retrieve maintenanceProcedureOperationLabel with maintenanceProcedureOperationLabelId: {id} from server {self._server}:{self._port}')
                response: MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelByIdResponse = stub.maintenance_procedure_operation_label_by_id.with_call(
                    MaintenanceProcedureOperationLabelAppService_maintenanceProcedureOperationLabelByIdRequest(id=id),
                    metadata=(('token', self.token), (
                        'opentel', AppDi.instance.get(OpenTelemetry).serializedContext(
                            MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabelById.__qualname__))))
                logger.debug(
                    f'[{MaintenanceProcedureOperationLabelClient.maintenanceProcedureOperationLabelById.__qualname__}] - grpc response: {response}')
                maintenanceProcedureOperationLabel = response[0].maintenance_procedure_operation_label
                return self._descriptorByObject(obj=maintenanceProcedureOperationLabel)
            except Exception as e:
                channel.unsubscribe(lambda ch: ch.close())
                raise e

    def _descriptorByObject(self, obj: Any) -> MaintenanceProcedureOperationLabelDescriptor:
        return MaintenanceProcedureOperationLabelDescriptor(id=obj.id,
                                      label=obj.label,
                                      generate_alert=obj.generate_alert,
                                      maintenance_procedure_operation_id=obj.maintenance_procedure_operation_id,
                                      )
