@startuml "system_c4model"
!include puml/c4_container.puml
!include puml/c4_component.puml

skinparam wrapWidth 200
skinparam maxMessageSize 200

LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()


Container_Boundary(redis, "Redis System") {
	Component(api__redis, "Api Caching & Response", "tcp", "Has response, caching results")
}
Container_Boundary(api, "Api Microservice") {
	ComponentQueue(api__identity_user_py__resetUserPassword__api_command_topic, "CommonCommandConstant.RESET_USER_PASSWORD.value", "api command topic", "")
	ComponentQueue(api__identity_realm_py__delete__api_command_topic, "CommonCommandConstant.DELETE_REALM.value", "api command topic", "")
	Component(api__identity_user_py__create, "Create User", "http(s)", "")
	Component(api__identity_ou_py__create, "Create Ou", "http(s)", "")
	Component(api__auth_py__authenticate, "Authenticate a user", "json/https", "Authenticate a user")
	Component(api__identity_ou_py__update, "Update Ou", "http(s)", "")
	ComponentQueue(api__identity_user_py__create__api_command_topic, "CommonCommandConstant.CREATE_USER.value", "api command topic", "")
	ComponentQueue(api__identity_permission_py__create__api_command_topic, "CommonCommandConstant.CREATE_PERMISSION.value", "api command topic", "")
	ComponentQueue(api__identity_user_group_py__update__api_command_topic, "CommonCommandConstant.UPDATE_USER_GROUP.value", "api command topic", "")
	Component(api__identity_user_group_py__getUserGroups, "Get User Groups", "http(s)", "get all user groups")
	Component(api__identity_permission_context_py__create, "Create Permission Context", "http(s)", "")
	ComponentQueue(api__identity_role_py__create__api_command_topic, "CommonCommandConstant.CREATE_ROLE.value", "api command topic", "")
	Component(api__identity_user_py__setUserPassword, "Set User Password", "http(s)", "")
	Component(api__identity_permission_py__create, "Create Permission", "http(s)", "")
	Component(api__identity_ou_py__getOus, "Get Ous", "http(s)", "")
	Component(api__identity_user_py__resetUserPassword, "Reset User Password", "http(s)", "")
	Component(api__auth_py__logout, "logout", "json/https", "logout a user")
	ComponentQueue(api__identity_user_group_py__create__api_command_topic, "CommonCommandConstant.CREATE_USER_GROUP.value", "api command topic", "")
	Component(api__identity_user_py__delete, "Delete User", http(s)", "")
	Component(api__identity_permission_py__getPermission, "Get Permission", "http(s)", "Get permission by id")
	Component(api__identity_role_py__getRoles, "Get Roles", "http(s)", "Get all roles")
	ComponentQueue(api__identity_role_py__update__api_command_topic, "CommonCommandConstant.DELETE_ROLE.value", "api command topic", "")
	ComponentQueue(api__identity_ou_py__delete__api_command_topic, "CommonCommandConstant.DELETE_OU.value", "api command topic", "")
	Component(api__identity_user_group_py__create, "Create User Group", "http(s)", "")
	Component(api__identity_realm_py__getRealms, "Get Realms", "http(s)", "")
	Component(api__identity_permission_context_py__getPermissionContexts, "Get Permission Contexts", "http(s)", "Get all permission contexts")
	ComponentQueue(api__identity_role_py__delete__api_command_topic, "CommonCommandConstant.DELETE_ROLE.value", "api command topic", "")
	Component(api__identity_permission_context_py__getPermissionContext, "Get Permission Context", "http(s)", "Get permission context by id")
	Component(api__identity_role_py__update, "Update Role", "http(s)", "")
	ComponentQueue(api__identity_project_py__delete__api_command_topic, "CommonCommandConstant.DELETE_PROJECT.value", "api command topic", "")
	ComponentQueue(api__identity_user_py__setUserPassword__api_command_topic, "CommonCommandConstant.SET_USER_PASSWORD.value", "api command topic", "")
	Component(api__identity_permission_context_py__delete, "Delete Permission Context", "http(s)", "")
	Component(api__identity_project_py__delete, "Delete Project", "http(s)", "")
	Component(api__identity_realm_py__delete, "Delete Realm", "http(s)", "")
	ComponentQueue(api__identity_user_group_py__delete__api_command_topic, "CommonCommandConstant.DELETE_USER_GROUP.value", "api command topic", "")
	ComponentQueue(api__identity_permission_context_py__create__api_command_topic, "CommonCommandConstant.CREATE_PERMISSION_CONTEXT.value", "api command topic", "")
	Component(api__identity_project_py__create, "Create Project", "http(s)", "")
	Component(api__identity_user_group_py__getUserGroup, "Get User Group", "http(s)", "get user group by id")
	Component(api__identity_permission_py__delete, "Delete Permission", "http(s)", "")
	ComponentQueue(api__identity_permission_context_py__update__api_command_topic, "CommonCommandConstant.UPDATE_RESOURCE_TYPE.value", "api command topic", "")
	Component(api__identity_role_py__getRole, "Get Role", "http(s)", "Get role by id")
	Component(api__identity_permission_py__update, "Update Permission", "http(s)", "")
	Component(api__identity_realm_py__update, "Update Realm", "http(s)", "")
	Component(api__identity_ou_py__delete, "Delete Ou", "http(s)", "")
	Component(api__identity_permission_py__getPermissions, "Get Permissions", "http(s)", "Get all permissions")
	Component(api__identity_project_py__getProject, "Get Project", "http(s)", "Get project by id")
	ComponentQueue(api__identity_permission_context_py__delete__api_command_topic, "CommonCommandConstant.DELETE_RESOURCE_TYPE.value", "api command topic", "")
	ComponentQueue(api__identity_ou_py__update__api_command_topic, "CommonCommandConstant.UPDATE_OU.value", "api command topic", "")
	ComponentQueue(api__identity_permission_py__update__api_command_topic, "CommonCommandConstant.UPDATE_PERMISSION.value", "api command topic", "")
	ComponentQueue(api__identity_realm_py__update__api_command_topic, "CommonCommandConstant.UPDATE_REALM.value", "api command topic", "")
	Component(api__identity_permission_context_py__update, "Update Permission Context", "http(s)", "")
	ComponentQueue(api__identity_permission_py__delete__api_command_topic, "CommonCommandConstant.DELETE_PERMISSION.value", "api command topic", "")
	Component(api__identity_ou_py__getOu, "Get Ou", "http(s)", "Get ou by id")
	Component(api__identity_role_py__delete, "Delete Role", "http(s)", "")
	ComponentQueue(api__identity_ou_py__create__api_command_topic, "CommonCommandConstant.CREATE_OU.value", "api command topic", "")
	Component(api__project_project_py__update, "Update Project", "http(s)", "")
	ComponentQueue(api__project_project_py__update__api_command_topic, "CommonCommandConstant.UPDATE_PROJECT.value", "api command topic", "")
	ComponentQueue(api__identity_realm_py__create__api_command_topic, "CommonCommandConstant.CREATE_REALM.value", "api command topic", "")
	Component(api__identity_realm_py__getRealm, "Get Realm", "http(s)", "Get realm by id")
	Component(api__identity_user_group_py__delete, "Delete User Group", "http(s)", "")
	ComponentQueue(api__identity_user_py__delete__api_command_topic, "CommonCommandConstant.DELETE_USER.value", "api command topic", "")
	ComponentQueue(api__identity_project_py__create__api_command_topic, "CommonCommandConstant.CREATE_PROJECT.value", "api command topic", "")
	Component(api__identity_user_py__getUser, "Get User", "http(s)", "Get user by id")
	Component(api__identity_realm_py__create, "Create Realm", "http(s)", "")
	Component(api__identity_project_py__getProjects, "Get Projects", "http(s)", "Get all projects")
	Component(api__identity_user_py__getUsers, "Get Users", "http(s)", "Get all users")
	Component(api__identity_role_py__create, "Create Role", "http(s)", "")
	Component(api__identity_user_group_py__update, "Update User Group", "http(s)", "")
}
Container_Boundary(identity, "Identity Microservice") {
	ComponentQueue(identity__domainmodel_event__UserGroupCreated, "CommonEventConstant.USER_GROUP_CREATED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__PermissionUpdated, "CommonEventConstant.PERMISSION_UPDATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateOuHandler, "CommonCommandConstant.UPDATE_OU.value", "api command consumer", "")
	ComponentQueue(identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "CommonEventConstant.DELETE_USER_ONE_TIME_PASSWORD.value", "identity command consumer", "")
	ComponentQueue(identity__domainmodel_event__RealmCreated, "CommonEventConstant.REALM_CREATED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__UserGroupUpdated, "CommonEventConstant.USER_GROUP_UPDATED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__OuDeleted, "CommonEventConstant.OU_DELETED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionHandler, "CommonCommandConstant.DELETE_PERMISSON.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__DeleteOuHandler, "CommonCommandConstant.DELETE_OU.value", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserWithOneTimePasswordLoggedIn, "CommonEventConstant.USER_WITH_ONE_TIME_PASSWORD_LOGGED_IN.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__RealmDeleted, "CommonEventConstant.REALM_DELETED.value", "message", "event")
	Component(identity__grpc__UserAppServiceListener__users, "Get users", "grpc listener", "Get all users")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionContextHandler, "CommonCommandConstant.CREATE_PERMISSON_CONTEXT.value", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__UserCreated, "CommonEventConstant.USER_CREATED.value", "message", "event")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	ComponentQueue(identity__domainmodel_event__PermissionContextCreated, "CommonEventConstant.PERMISSION_CONTEXT_CREATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreatePermissionHandler, "CommonCommandConstant.CREATE_PERMISSON.value", "api command consumer", "")
	Component(identity__grpc__UserAppServiceListener__userById, "Get user by id", "grpc listener", "Get a user by id")
	ComponentQueue(identity__domainmodel_event__PermissionDeleted, "CommonEventConstant.PERMISSION_DELETED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__PermissionCreated, "CommonEventConstant.PERMISSION_CREATED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssigned, "CommonEventConstant.ROLE_TO_USER_ASSIGNED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__OuCreated, "CommonEventConstant.OU_CREATED.value", "message", "event")
	Component(identity__grpc__PermissionAppServiceListener__permissionById, "Get permission by id", "grpc listener", "Get a permission by id")
	ComponentQueue(identity__domainmodel_event__RealmUpdated, "CommonEventConstant.REALM_UPDATED.value", "message", "event")
	Component(identity__grpc__AuthAppServiceListener__logout, "Logout user", "grpc listener", "Logout a user")
	ComponentQueue(identity__domainmodel_event__RoleCreated, "CommonEventConstant.ROLE_CREATED.value", "message", "event")
	Component(identity__grpc__RealmAppServiceListener__realmById, "Get realm by id", "grpc listener", "Get a realm by id")
	ComponentQueue(identity__domainmodel_event__UserOneTimePasswordGenerated, "CommonEventConstant.USER_ONE_TIME_PASSWORD_GENERATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRoleHandler, "CommonCommandConstant.DELETE_ROLE.value", "api command consumer", "")
	ComponentQueue(identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "CommonEventConstant.SEND_EMAIL_ONE_TIME_USER_PASSWORD.value", "identity command consumer", "")
	ComponentQueue(identity__domainmodel_event__RoleToUserAssignmentRevoked, "CommonEventConstant.ROLE_TO_USER_ASSIGNMENT_REVOKED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__DeleteProjectHandler, "CommonCommandConstant.DELETE_PROJECT.value", "api command consumer", "")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserHandler, "CommonCommandConstant.DELETE_USER.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionHandler, "CommonCommandConstant.UPDATE_PERMISSON.value", "api command consumer", "")
	Component(identity__grpc__CountryAppServiceListener__cityByCountryId, "Get city by country id", "grpc listener", "Get a city by country id")
	Component(identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc listener", "Get all realms")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssigned, "CommonEventConstant.USER_TO_REALM_ASSIGNED.value", "message", "event")
	Component(identity__grpc__PermissionAppServiceListener__permissions, "Get permission", "grpc listener", "Get all permissions")
	ComponentQueue(identity__domainmodel_event__PermissionContextUpdated, "CommonEventConstant.PERMISSION_CONTEXT_UPDATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreateRoleHandler, "CommonCommandConstant.CREATE_ROLE.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateOuHandler, "CommonCommandConstant.CREATE_OU.value", "api command consumer", "")
	Component(identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc listener", "Get all ous")
	Component(identity__grpc__RoleAppServiceListener__roleById, "Get role by id", "grpc listener", "Get a role by id")
	ComponentQueue(identity__domainmodel_event__UserDeleted, "CommonEventConstant.USER_CREATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRoleHandler, "CommonCommandConstant.UPDATE_ROLE.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateProjectHandler, "CommonCommandConstant.CREATE_PROJECT.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateRealmHandler, "CommonCommandConstant.CREATE_REALM.value", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__RoleUpdated, "CommonEventConstant.ROLE_UPDATED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__ProjectDeleted, "CommonEventConstant.PROJECT_DELETED.value", "message", "event")
	Component(identity__grpc__CountryAppServiceListener__citiesByCountryId, "Get cities by country id", "grpc listener", "Get cities by country id")
	ComponentQueue(identity__domainmodel_event__ProjectUpdated, "CommonEventConstant.PROJECT_UPDATED.value", "message", "event")
	ComponentQueue(identity__messaging_project_event_handler__UserCreatedHandler, "CommonEventConstant.USER_CREATED.value", "project event consumer", "Generate user one time password")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get permission context by id", "grpc listener", "Get a permission context by id")
	ComponentQueue(identity__domainmodel_event__UserPasswordSet, "CommonEventConstant.USER_PASSWORD_SET.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateRealmHandler, "CommonCommandConstant.UPDATE_REALM.value", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__RoleDeleted, "CommonEventConstant.ROLE_DELETED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserGroupHandler, "CommonCommandConstant.CREATE_USER_GROUP.value", "api command consumer", "")
	Component(identity__grpc__UserGroupAppServiceListener__userGroupById, "Get user group by id", "grpc listener", "Get a user group by id")
	ComponentQueue(identity__domainmodel_event__UserToRealmAssignmentRevoked, "CommonEventConstant.USER_TO_REALM_ASSIGNMENT_REVOKED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__UserGroupDeleted, "CommonEventConstant.USER_GROUP_DELETED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__SetUserPasswordHandler, "CommonCommandConstant.SET_USER_PASSWORD.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__UpdateUserGroupHandler, "CommonCommandConstant.UPDATE_USER_GROUP.value", "api command consumer", "")
	ComponentQueue(identity__domainmodel_event__OuUpdated, "CommonEventConstant.OU_UPDATED.value", "message", "event")
	Component(identity__grpc__CityAppServiceListener__cityById, "Get city by id", "grpc listener", "Get a city by id")
	Component(identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc listener", "Get all permission contexts")
	ComponentQueue(identity__messaging_api_command_handler__UpdatePermissionContextHandler, "CommonCommandConstant.UPDATE_RESOURCE_TYPE.value", "api command consumer", "")
	Component(identity__grpc__OuAppServiceListener__ouById, "Get ou by id", "grpc listener", "Get a ou by id")
	ComponentQueue(identity__domainmodel_event__PermissionContextDeleted, "CommonEventConstant.PERMISSION_CONTEXT_DELETED.value", "message", "event")
	ComponentQueue(identity__domainmodel_event__ProjectCreated, "CommonEventConstant.PROJECT_CREATED.value", "message", "event")
	Component(identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc listener", "Get all user groups")
	ComponentQueue(identity__messaging_api_command_handler__DeleteRealmHandler, "CommonCommandConstant.DELETE_REALM.value", "api command consumer", "")
	Component(identity__grpc__CityAppServiceListener__cities, "Get cities", "grpc listener", "Get all cities")
	Component(identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc listener", "Get all roles")
	ComponentQueue(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, "CommonEventConstant.USER_WITH_ONE_TIME_PASSWORD_LOGGED_IN.value", "identity event consumer", "")
	Component(identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user by email and password", "grpc listener", "Authenticate a user")
	ComponentQueue(identity__domainmodel_event__UserUpdated, "CommonEventConstant.USER_UPDATED.value", "message", "event")
	ComponentQueue(identity__messaging_api_command_handler__UpdateProjectHandler, "CommonCommandConstant.UPDATE_PROJECT.value", "api command consumer", "")
	ComponentQueue(identity__messaging_project_event_handler__UserUpdatedHandler, "CommonEventConstant.USER_UPDATED.value", "project event consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__CreateUserHandler, "CommonCommandConstant.CREATE_USER.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__ResetUserPasswordHandler, "CommonCommandConstant.RESET_USER_PASSWORD.value", "api command consumer", "")
	ComponentQueue(identity__messaging_api_command_handler__DeletePermissionContextHandler, "CommonCommandConstant.DELETE_RESOURCE_TYPE.value", "api command consumer", "")
	ComponentQueue(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, "CommonEventConstant.USER_ONE_TIME_PASSWORD_GENERATED.value", "identity event consumer", "")
	Component(identity__grpc__CountryAppServiceListener__countryById, "Get country by id", "grpc listener", "Get a country by id")
	ComponentQueue(identity__messaging_api_command_handler__DeleteUserGroupHandler, "CommonCommandConstant.DELETE_USER_GROUP.value", "api command consumer", "")
	Component(identity__grpc__CountryAppServiceListener__countries, "Get countries", "grpc listener", "Get all countries")
}
Container_Boundary(project, "Project Microservice") {
	ComponentQueue(project__domainmodel_event__UserDeleted, "User Deleted", "event", "message")
	ComponentQueue(project__domainmodel_event__ProjectDeleted, "Project Created", "event", "message")
	ComponentQueue(project__domainmodel_event__OrganizationCreated, "Organization Created", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__ProjectCreatedHandler, "CommonEventConstant.PROJECT_CREATED.value", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__OrganizationUpdated, "Organization Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__RoleUpdated, "Role Updated", "event", "message")
	ComponentQueue(project__domainmodel_event__ProjectCreated, "Project Created", "event", "message")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserId, "Get a user lookup by id", "grpc listener", "Get a user lookup by id")
	ComponentQueue(project__domainmodel_event__UserUpdated, "User Updated", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__UserCreatedHandler, "CommonEventConstant.USER_CREATED.value", "identity event consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, "CommonEventConstant.ROLE_TO_USER_ASSIGNMENT_REVOKED.value", "identity event consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignedHandler, "CommonEventConstant.USER_TO_REALM_ASSIGNED.value", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssignmentRevoked, "User to Organization Assignment Revoked", "event", "message")
	Component(identity__grpc__OrganizationAppServiceListener__organizations, "Get organizations", "grpc listener", "Get all organizations")
	ComponentQueue(project__messaging_project_command_handler__CreateProjectHandler, "CommonCommandConstant.CREATE_PROJECT.value", "project command consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__UserUpdatedHandler, "CommonEventConstant.USER_UPDATED.value", "identity event consumer", "User updated")
	ComponentQueue(project__messaging_project_command_handler__DeleteOrganizationHandler, "CommonCommandConstant.DELETE_ORGANIZATION.value", "project command consumer", "")
	Component(identity__grpc__UserAppServiceListener__userById, "Get a user by id", "grpc listener", "Get a user by id")
	Component(identity__grpc__UserLookupAppServiceListener__userLookups, "Get a user lookups", "grpc listener", "Get user lookups")
	ComponentQueue(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "CommonCommandConstant.REVOKE_ROLE_TO_USER_ASSIGNMENT.value", "project command consumer", "Revoke Role to User Assignment")
	ComponentQueue(project__domainmodel_event__ProjectStateChanged, "Project State Changed", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__DeleteOrganizationHandler, "Delete Organization", "project command consumer", "Delete Organization")
	Component(identity__grpc__ProjectAppServiceListener__projectById, "Get project by id", "grpc listener", "Get a project by id")
	ComponentQueue(project__domainmodel_event__RoleToUserAssignmentRevoked, "Role to User Assignment Revoked", "event", "message")
	Component(identity__grpc__OrganizationAppServiceListener__organizationById, "Get organization by id", "grpc listener", "Get a organization by id")
	ComponentQueue(project__domainmodel_event__UserToOrganizationAssigned, "User to Organization Assigned", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__DeleteUserHandler, "CommonCommandConstant.DELETE_USER.value", "project command consumer", "")
	ComponentQueue(project__domainmodel_event__ProjectUpdated, "Project Updated", "event", "message")
	Component(identity__grpc__ProjectAppServiceListener__projectByName, "Get project by name", "grpc listener", "Get a project by name")
	ComponentQueue(project__domainmodel_event__RoleDeleted, "Role Deleted", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__UpdateOrganizationHandler, "CommonCommandConstant.UPDATE_ORGANIZATION.value", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__CreateUserHandler, "CommonCommandConstant.CREATE_USER.value", "project command consumer", "Create User")
	Component(identity__grpc__UserLookupAppServiceListener__userLookupByUserEmail, "Get a user lookup by email", "grpc listener", "Get a user lookup by email")
	ComponentQueue(project__domainmodel_event__RoleToUserAssigned, "Role to User Assigned", "event", "message")
	ComponentQueue(project__messaging_project_command_handler__AssignRoleToUserHandler, "CommonCommandConstant.ASSIGN_ROLE_TO_USER.value", "project command consumer", "")
	Component(identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc listener", "Get all projects")
	ComponentQueue(project__messaging_project_command_handler__CreateOrganizationHandler, "CommonCommandConstant.CREATE_ORGANIZATION.value", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__CreateRoleHandler, "CommonCommandConstant.CREATE_ROLE.value", "project command consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, "CommonEventConstant.USER_TO_REALM_ASSIGNMENT_REVOKED.value", "identity event consumer", "")
	Component(identity__grpc__UserAppServiceListener__users, "Get all users", "grpc listener", "Get users")
	ComponentQueue(project__messaging_identity_event_handler__UserDeletedHandler, "CommonEventConstant.USER_DELETED.value", "identity event consumer", "")
	ComponentQueue(project__domainmodel_event__UserCreated, "User Created", "event", "message")
	ComponentQueue(project__messaging_identity_event_handler__ProjectDeletedHandler, "CommonEventConstant.PROJECT_DELETED.value", "identity event consumer", "Project deleted")
	ComponentQueue(project__messaging_project_command_handler__UpdateUserHandler, "CommonCommandConstant.UPDATE_USER.value", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "CommonCommandConstant.REVOKE_USER_TO_ORGANIZATION_ASSIGNMENT.value", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__UpdateOrganizationHandler, "Update Organization", "project command consumer", "Update Organization")
	ComponentQueue(project__messaging_identity_event_handler__RoleToUserAssignedHandler, "CommonEventConstant.ROLE_TO_USER_ASSIGNED.value", "identity event consumer", "")
	ComponentQueue(project__messaging_identity_event_handler__RealmCreatedHandler, "CommonEventConstant.REALM_CREATED.value", "identity event consumer", "")
	ComponentQueue(project__messaging_project_command_handler__DeleteProjectHandler, "CommonCommandConstant.DELETE_PROJECT.value", "project command consumer", "")
	ComponentQueue(project__messaging_project_command_handler__AssignUserToOrganizationHandler, "CommonCommandConstant.ASSIGN_USER_TO_ORGANIZATION.value", "project command consumer", "")
	ComponentQueue(project__domainmodel_event__RoleCreated, "Role Created", "event", "message")
	ComponentQueue(project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "event", "message")
	Component(identity__grpc__UserAppServiceListener__userByEmail, "Get a user by email", "grpc listener", "Get a user by email")
	ComponentQueue(project__messaging_identity_event_handler__RoleCreatedHandler, "CommonEventConstant.ROLE_CREATED.value", "identity event consumer", "")
}
Rel(identity__messaging_api_command_handler__UpdatePermissionHandler, identity__domainmodel_event__PermissionUpdated, "create")
Rel(project__messaging_identity_event_handler__RealmCreatedHandler, project__messaging_project_command_handler__CreateOrganizationHandler, "CommonCommandConstant.CREATE_ORGANIZATION.value", "message")
Rel(api__identity_project_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteProjectHandler, "CommonCommandConstant.DELETE_PROJECT.value", "message")
Rel(api__identity_permission_py__create, api__identity_permission_py__create__api_command_topic, "CommonCommandConstant.CREATE_PERMISSION.value", "message")
Rel(api__project_project_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateProjectHandler, "CommonCommandConstant.UPDATE_PROJECT.value", "message")
Rel(api__identity_role_py__create__api_command_topic, identity__messaging_api_command_handler__CreateRoleHandler, "CommonCommandConstant.CREATE_ROLE.value", "message")
Rel(api__identity_permission_py__getPermission, identity__grpc__PermissionAppServiceListener__permissionById, "Get permission by id", "grpc")
Rel(api__identity_user_py__getUser, identity__grpc__UserAppServiceListener__userById, "Get user by id", "grpc")
Rel(identity__messaging_api_command_handler__DeleteRoleHandler, identity__domainmodel_event__RoleDeleted, "create")
Rel(api__identity_ou_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateOuHandler, "CommonCommandConstant.UPDATE_OU.value", "message")
Rel(api__identity_permission_context_py__create__api_command_topic, identity__messaging_api_command_handler__CreatePermissionContextHandler, "CommonCommandConstant.CREATE_PERMISSON_CONTEXT.value", "message")
Rel(api__identity_realm_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteRealmHandler, "CommonCommandConstant.DELETE_REALM.value", "message")
Rel(project__messaging_project_command_handler__UpdateOrganizationHandler, project__domainmodel_event__OrganizationUpdated, "create")
Rel(project__messaging_identity_event_handler__UserToRealmAssignedHandler, project__messaging_project_command_handler__AssignUserToOrganizationHandler, "CommonCommandConstant.ASSIGN_USER_TO_ORGANIZATION.value", "message")
Rel(identity__messaging_api_command_handler__CreateOuHandler, identity__domainmodel_event__OuCreated, "create")
Rel(identity__messaging_api_command_handler__CreateUserGroupHandler, identity__domainmodel_event__UserGroupCreated, "create")
Rel(identity__messaging_identity_event_handler__UserOneTimePasswordGeneratedHandler, identity__messaging_identity_command_handler__SendEmailOneTimeUserPasswordHandler, "CommonCommandConstant.SEND_EMAIL_ONE_TIME_USER_PASSWORD.value", "message")
Rel(project__messaging_project_command_handler__CreateProjectHandler, project__domainmodel_event__ProjectCreated, "create", "message")
Rel(project__messaging_identity_event_handler__RoleCreatedHandler, project__messaging_project_command_handler__CreateRoleHandler, "CommonCommandConstant.CREATE_ROLE.value", "message")
Rel(api__identity_user_py__setUserPassword__api_command_topic, identity__messaging_api_command_handler__ResetUserPasswordHandler, "CommonCommandConstant.RESET_USER_PASSWORD.value", "message")
Rel(api__identity_permission_context_py__getPermissionContext, identity__grpc__PermissionContextAppServiceListener__permissionContextById, "Get permission context by id", "grpc")
Rel(api__identity_permission_context_py__delete, api__identity_permission_context_py__delete__api_command_topic, "CommonCommandConstant.DELETE_RESOURCE_TYPE.value", "message")
Rel(api__identity_permission_py__create__api_command_topic, identity__messaging_api_command_handler__CreatePermissionHandler, "CommonCommandConstant.CREATE_PERMISSON.value", "message")
Rel(api__identity_ou_py__getOu, identity__grpc__OuAppServiceListener__ouById, "Get ou by id", "grpc")
Rel(api__identity_role_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteRoleHandler, "CommonCommandConstant.DELETE_ROLE.value", "message")
Rel(api__identity_realm_py__create, api__identity_realm_py__create__api_command_topic, "CommonCommandConstant.CREATE_REALM.value", "message")
Rel(identity__messaging_api_command_handler__UpdateRealmHandler, identity__domainmodel_event__RealmUpdated, "create")
Rel(api__identity_project_py__create, api__identity_project_py__create__api_command_topic, "CommonCommandConstant.CREATE_PROJECT.value", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, identity__domainmodel_event__UserToRealmAssignmentRevoked, "consume")
Rel(api__identity_user_group_py__delete, api__identity_user_group_py__delete__api_command_topic, "CommonCommandConstant.DELETE_USER_GROUP.value", "message")
Rel(api__identity_role_py__update, api__identity_role_py__update__api_command_topic, "CommonCommandConstant.DELETE_ROLE.value", "message")
Rel(api__identity_user_group_py__create__api_command_topic, identity__messaging_api_command_handler__CreateUserGroupHandler, "CommonCommandConstant.CREATE_USER_GROUP.value", "message")
Rel(project__messaging_identity_event_handler__ProjectDeletedHandler, identity__domainmodel_event__ProjectDeleted, "consume")
Rel(api__identity_user_py__create, api__identity_user_py__create__api_command_topic, "CommonCommandConstant.CREATE_USER.value", "message")
Rel(api__identity_permission_context_py__update, api__identity_permission_context_py__update__api_command_topic, "CommonCommandConstant.UPDATE_RESOURCE_TYPE.value", "message")
Rel(api__identity_permission_py__update, api__identity_permission_py__update__api_command_topic, "CommonCommandConstant.UPDATE_PERMISSION.value", "message")
Rel(api__identity_realm_py__create__api_command_topic, identity__messaging_api_command_handler__CreateRealmHandler, "CommonCommandConstant.CREATE_REALM.value", "message")
Rel(api__identity_permission_py__update__api_command_topic, identity__messaging_api_command_handler__UpdatePermissionHandler, "CommonCommandConstant.UPDATE_PERMISSON.value", "message")
Rel(identity__messaging_api_command_handler__CreateRoleHandler, identity__domainmodel_event__RoleCreated, "create")
Rel(project__messaging_project_command_handler__DeleteUserHandler, project__domainmodel_event__UserDeleted, "create")
Rel(api__identity_user_group_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateUserGroupHandler, "CommonCommandConstant.UPDATE_USER_GROUP.value", "message")
Rel(project__messaging_project_command_handler__DeleteOrganizationHandler, project__domainmodel_event__OrganizationDeleted, "create")
Rel(project__messaging_identity_event_handler__ProjectDeletedHandler, project__messaging_project_command_handler__DeleteProjectHandler, "CommonCommandConstant.DELETE_PROJECT.value", "message")
Rel(project__messaging_project_command_handler__AssignUserToOrganizationHandler, project__domainmodel_event__UserToOrganizationAssigned, "create")
Rel(project__messaging_identity_event_handler__RoleToUserAssignedHandler, identity__domainmodel_event__RoleToUserAssigned, "consume")
Rel(api__identity_realm_py__getRealms, identity__grpc__RealmAppServiceListener__realms, "Get realms", "grpc")
Rel(project__messaging_project_command_handler__AssignRoleToUserHandler, project__domainmodel_event__RoleToUserAssigned, "create")
Rel(api__identity_project_py__getProjects, identity__grpc__ProjectAppServiceListener__projects, "Get projects", "grpc")
Rel(project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, project__domainmodel_event__RoleToUserAssignmentRevoked, "create")
Rel(api__identity_user_py__delete, api__identity_user_py__delete__api_command_topic, "CommonCommandConstant.DELETE_USER.value", "message")
Rel(api__identity_ou_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteOuHandler, "CommonCommandConstant.DELETE_OU.value", "message")
Rel(api__identity_user_py__setUserPassword, api__identity_user_py__setUserPassword__api_command_topic, "CommonCommandConstant.SET_USER_PASSWORD.value", "message")
Rel(project__messaging_project_command_handler__DeleteProjectHandler, project__domainmodel_event__ProjectDeleted, "create")
Rel(project__messaging_project_command_handler__UpdateUserHandler, project__domainmodel_event__UserUpdated, "create")
Rel(api__identity_role_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateRoleHandler, "CommonCommandConstant.UPDATE_ROLE.value", "message")
Rel(project__messaging_identity_event_handler__UserToRealmAssignedHandler, identity__domainmodel_event__UserToRealmAssigned, "consume")
Rel(identity__messaging_api_command_handler__DeleteUserHandler, identity__domainmodel_event__UserDeleted, "create")
Rel(identity__messaging_api_command_handler__UpdateOuHandler, identity__domainmodel_event__OuUpdated, "create")
Rel(api__identity_ou_py__getOus, identity__grpc__OuAppServiceListener__ous, "Get ous", "grpc")
Rel(project__messaging_identity_event_handler__UserCreatedHandler, identity__domainmodel_event__UserCreated, "consume")
Rel(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, identity__messaging_identity_command_handler__DeleteUserOneTimePasswordHandler, "CommonCommandConstant.DELETE_USER_ONE_TIME_PASSWORD.value", "message")
Rel(project__messaging_identity_event_handler__ProjectCreatedHandler, project__messaging_project_command_handler__CreateProjectHandler, "CommonCommandConstant.CREATE_PROJECT.value", "message")
Rel(api__identity_permission_context_py__delete__api_command_topic, identity__messaging_api_command_handler__DeletePermissionContextHandler, "CommonCommandConstant.DELETE_RESOURCE_TYPE.value", "message")
Rel(project__messaging_identity_event_handler__UserDeletedHandler, project__messaging_project_command_handler__DeleteUserHandler, "CommonCommandConstant.DELETE_USER.value", "message")
Rel(api__auth_py__logout, identity__grpc__AuthAppServiceListener__logout, "Logout user by token", "grpc call")
Rel(api__identity_project_py__getProject, identity__grpc__ProjectAppServiceListener__projectById, "Get a project by id", "grpc")
Rel(api__identity_ou_py__delete, api__identity_ou_py__delete__api_command_topic, "CommonCommandConstant.DELETE_OU.value", "message")
Rel(api__identity_user_py__resetUserPassword, api__identity_user_py__resetUserPassword__api_command_topic, "CommonCommandConstant.RESET_USER_PASSWORD.value", "message")
Rel(api__identity_project_py__delete, api__identity_project_py__delete__api_command_topic, "CommonCommandConstant.DELETE_PROJECT.value", "message")
Rel(api__identity_user_group_py__update, api__identity_user_group_py__update__api_command_topic, "CommonCommandConstant.UPDATE_USER_GROUP.value", "message")
Rel(api__identity_ou_py__create__api_command_topic, identity__messaging_api_command_handler__CreateOuHandler, "CommonCommandConstant.CREATE_OU.value", "message")
Rel(identity__messaging_api_command_handler__SetUserPasswordHandler, identity__messaging_api_command_handler__SetUserPasswordHandler, "CommonCommandConstant.SET_USER_PASSWORD.value", "message")
Rel(api__identity_role_py__create, api__identity_role_py__create__api_command_topic, "CommonCommandConstant.CREATE_ROLE.value", "message")
Rel(api__identity_permission_py__getPermissions, identity__grpc__PermissionAppServiceListener__permissions, "Get permissions", "grpc")
Rel(project__messaging_project_command_handler__UpdateOrganizationHandler, project__domainmodel_event__OrganizationUpdated, "Organization Updated", "message")
Rel(api__identity_permission_context_py__update__api_command_topic, identity__messaging_api_command_handler__UpdatePermissionContextHandler, "CommonCommandConstant.UPDATE_RESOURCE_TYPE.value", "message")
Rel(identity__messaging_api_command_handler__DeleteUserGroupHandler, identity__domainmodel_event__UserGroupUpdated, "create")
Rel(identity__messaging_api_command_handler__DeleteUserGroupHandler, identity__domainmodel_event__UserGroupDeleted, "create")
Rel(api__identity_realm_py__getRealm, identity__grpc__RealmAppServiceListener__realmById, "Get realm by id", "grpc")
Rel(project__messaging_project_command_handler__CreateRoleHandler, project__domainmodel_event__RoleCreated, "create")
Rel(project__messaging_identity_event_handler__RoleCreatedHandler, identity__domainmodel_event__RoleCreated, "consume")
Rel(api__identity_user_py__resetUserPassword__api_command_topic, identity__messaging_api_command_handler__ResetUserPasswordHandler, "CommonCommandConstant.RESET_USER_PASSWORD.value", "message")
Rel(identity__messaging_api_command_handler__DeletePermissionHandler, identity__domainmodel_event__PermissionDeleted, "create")
Rel(identity__messaging_api_command_handler__CreatePermissionHandler, identity__domainmodel_event__PermissionCreated, "create")
Rel(identity__messaging_api_command_handler__DeleteProjectHandler, identity__domainmodel_event__ProjectDeleted, "create")
Rel(api__identity_ou_py__create, api__identity_ou_py__create__api_command_topic, "CommonCommandConstant.CREATE_OU.value", "message")
Rel(identity__messaging_api_command_handler__UpdatePermissionContextHandler, identity__domainmodel_event__PermissionContextUpdated, "create")
Rel(identity__messaging_api_command_handler__ResetUserPasswordHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "create")
Rel(project__messaging_project_command_handler__DeleteOrganizationHandler, project__domainmodel_event__OrganizationDeleted, "Organization Deleted", "message")
Rel(api__identity_ou_py__update, api__identity_ou_py__update__api_command_topic, "CommonCommandConstant.UPDATE_OU.value", "message")
Rel(api__identity_realm_py__update, api__identity_realm_py__update__api_command_topic, "CommonCommandConstant.UPDATE_REALM.value", "message")
Rel(api__project_project_py__update, api__project_project_py__update__api_command_topic, "CommonCommandConstant.UPDATE_PROJECT.value", "message")
Rel(api__identity_user_group_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteUserGroupHandler, "CommonCommandConstant.DELETE_USER_GROUP.value", "message")
Rel(api__identity_role_py__delete, api__identity_role_py__delete__api_command_topic, "CommonCommandConstant.DELETE_ROLE.value", "message")
Rel(project__messaging_project_command_handler__CreateOrganizationHandler, project__domainmodel_event__OrganizationCreated, "create")
Rel(identity__messaging_identity_event_handler__UserWithOneTimePasswordLoggedInHandler, identity__domainmodel_event__UserWithOneTimePasswordLoggedIn, "consume")
Rel(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, identity__domainmodel_event__RoleToUserAssignmentRevoked, "consume")
Rel(identity__messaging_api_command_handler__DeleteOuHandler, identity__domainmodel_event__OuDeleted, "create")
Rel(project__messaging_identity_event_handler__UserDeletedHandler, identity__domainmodel_event__UserDeleted, "consume")
Rel(api__identity_role_py__getRoles, identity__grpc__RoleAppServiceListener__roles, "Get roles", "grpc")
Rel(api__identity_permission_context_py__getPermissionContexts, identity__grpc__PermissionContextAppServiceListener__permissionContexts, "Get permission contexts", "grpc")
Rel(api__identity_realm_py__update__api_command_topic, identity__messaging_api_command_handler__UpdateRealmHandler, "CommonCommandConstant.UPDATE_REALM.value", "message")
Rel(project__messaging_identity_event_handler__ProjectCreatedHandler, identity__domainmodel_event__ProjectCreated, "consume")
Rel(api__identity_user_py__delete__api_command_topic, identity__messaging_api_command_handler__DeleteUserHandler, "CommonCommandConstant.DELETE_USER.value", "message")
Rel(api__identity_user_py__getUsers, identity__grpc__UserAppServiceListener__users, "Get users", "grpc")
Rel(project__messaging_identity_event_handler__RoleToUserAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeRoleToUserAssignmentHandler, "CommonCommandConstant.REVOKE_ROLE_TO_USER_ASSIGNMENT.value", "message")
Rel(project__messaging_identity_event_handler__RoleToUserAssignedHandler, project__messaging_project_command_handler__AssignRoleToUserHandler, "CommonCommandConstant.ASSIGN_ROLE_TO_USER.value", "message")
Rel(api__identity_user_py__create__api_command_topic, identity__messaging_api_command_handler__CreateUserHandler, "CommonCommandConstant.CREATE_USER.value", "message")
Rel(project__messaging_identity_event_handler__UserUpdatedHandler, identity__domainmodel_event__UserUpdated, "consume")
Rel(identity__messaging_project_event_handler__UserUpdatedHandler, identity__domainmodel_event__UserUpdated, "create")
Rel(identity__messaging_api_command_handler__CreateUserHandler, identity__domainmodel_event__UserCreated, "create")
Rel(api__identity_user_group_py__getUserGroup, identity__grpc__UserGroupAppServiceListener__userGroupById, "Get user group by id", "grpc")
Rel(identity__messaging_api_command_handler__UpdateProjectHandler, identity__domainmodel_event__ProjectUpdated, "create")
Rel(api__identity_user_group_py__getUserGroups, identity__grpc__UserGroupAppServiceListener__userGroups, "Get user groups", "grpc")
Rel(project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, project__domainmodel_event__UserToOrganizationAssignmentRevoked, "create")
Rel(api__identity_project_py__create__api_command_topic, identity__messaging_api_command_handler__CreateProjectHandler, "CommonCommandConstant.CREATE_PROJECT.value", "message")
Rel(project__messaging_identity_event_handler__UserCreatedHandler, project__messaging_project_command_handler__CreateUserHandler, "CommonCommandConstant.CREATE_USER.value", "message")
Rel(identity__messaging_api_command_handler__CreateProjectHandler, identity__domainmodel_event__ProjectCreated, "create")
Rel(project__messaging_identity_event_handler__UserUpdatedHandler, project__messaging_project_command_handler__UpdateUserHandler, "CommonCommandConstant.UPDATE_USER.value", "message")
Rel(api__identity_permission_context_py__create, api__identity_permission_context_py__create__api_command_topic, "CommonCommandConstant.CREATE_PERMISSION_CONTEXT.value", "message")
Rel(api__identity_realm_py__delete, api__identity_realm_py__delete__api_command_topic, "CommonCommandConstant.DELETE_REALM.value", "message")
Rel(identity__messaging_api_command_handler__DeleteRealmHandler, identity__domainmodel_event__RealmDeleted, "create")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "consume")
Rel(project__messaging_identity_event_handler__RealmCreatedHandler, identity__domainmodel_event__RealmCreated, "consume")
Rel(identity__messaging_api_command_handler__CreateRealmHandler, identity__domainmodel_event__RealmCreated, "create")
Rel(api__identity_permission_py__delete, api__identity_permission_py__delete__api_command_topic, "CommonCommandConstant.DELETE_PERMISSION.value", "message")
Rel(api__identity_user_group_py__create, api__identity_user_group_py__create__api_command_topic, "CommonCommandConstant.CREATE_USER_GROUP.value", "message")
Rel(identity__messaging_project_event_handler__UserUpdatedHandler, project__domainmodel_event__UserUpdated, "consume")
Rel(identity__messaging_api_command_handler__DeletePermissionContextHandler, identity__domainmodel_event__PermissionContextDeleted, "create")
Rel(identity__messaging_api_command_handler__CreatePermissionContextHandler, identity__domainmodel_event__PermissionContextCreated, "create")
Rel(api__identity_role_py__getRole, identity__grpc__RoleAppServiceListener__roleById, "Get role by id", "grpc")
Rel(api__auth_py__authenticate, identity__grpc__AuthAppServiceListener__authenticateUserByEmailAndPassword, "Auth user & get token", "grpc call")
Rel(api__identity_permission_py__delete__api_command_topic, identity__messaging_api_command_handler__DeletePermissionHandler, "CommonCommandConstant.DELETE_PERMISSON.value", "message")
Rel(project__messaging_project_command_handler__CreateUserHandler, project__domainmodel_event__UserCreated, "create")
Rel(project__messaging_identity_event_handler__UserToRealmAssignmentRevokedHandler, project__messaging_project_command_handler__RevokeUserToOrganizationAssignmentHandler, "CommonCommandConstant.REVOKE_USER_TO_ORGANIZATION_ASSIGNMENT.value", "message")
Rel(identity__messaging_api_command_handler__UpdateRoleHandler, identity__domainmodel_event__RoleUpdated, "create")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, identity__domainmodel_event__UserOneTimePasswordGenerated, "create")
Rel(identity__messaging_project_event_handler__UserCreatedHandler, project__domainmodel_event__UserCreated, "consume")
Rel(api, redis, "Get/Create api response & caching data")

@enduml
