"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import List

from pydantic import BaseModel

from src.port_adapter.api.rest.model.response.v1.project.daily_check.procedure.DailyCheckProcedure import (
    DailyCheckProcedureDescriptor,
)


class DailyCheckProcedures(BaseModel):
    daily_check_procedures: List[DailyCheckProcedureDescriptor]
    item_count: int
