"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""
from pydantic import BaseModel


class DailyCheckProcedure(BaseModel):
    id: str
    name: str
    description: str
    project_id: str
    equipment_id: str
    equipment_category_group_id: str


class DailyCheckProcedureDescriptor(DailyCheckProcedure):
    pass
