"""
The file is generated by a scaffold script
@author: Arkan M. Gerges<arkan.m.gerges@gmail.com>
"""

from typing import Optional

from pydantic import BaseModel


class StandardMaintenanceProcedureOperationLabel(BaseModel):
    id: str
    label: str
    generate_alert: int
    standard_maintenance_procedure_operation_id: str


class StandardMaintenanceProcedureOperationLabelDescriptor(StandardMaintenanceProcedureOperationLabel):
    pass
